export type StageState = "approved" | "review" | "partial" | "running" | "pending" | "inactive" | "failed" | "live";

export interface StageNode {
  id: string;
  type: "prd" | "spec" | "tests" | "collection" | "deploy" | "metrics";
  label: string;
  title: string;
  state: StageState;
  connector: string;
  connectorColor: string;
  detail: string;
  stats?: string;
  actions: string[];
}

export interface Feature {
  id: string;
  name: string;
  team: string;
  stages: StageNode[];
}

export const FEATURES: Feature[] = [
  {
    id: "feat-1",
    name: "Reduce Checkout Friction",
    team: "Payments",
    stages: [
      {
        id: "prd-1", type: "prd", label: "PRD", title: "Reduce Checkout Friction",
        state: "approved", connector: "Linear", connectorColor: "#5e6ad2",
        detail: `**Problem**\nUsers abandon checkout at 40% due to multi-step friction.\n\n**Success Metrics**\n- Abandonment rate < 20%\n- Checkout time < 30s\n- NPS +15 points\n\n**Features**\n- One-click checkout for returning users\n- Remove mandatory 3DS for low-risk < $50\n- Autofill from saved payment methods`,
        actions: ["View in Linear", "Generate Spec"],
      },
      {
        id: "spec-1", type: "spec", label: "Tech Spec", title: "Payment API v2 Refactor",
        state: "review", connector: "Notion", connectorColor: "#ffffff",
        detail: `**Architecture**\nExtend payment-service with quick-checkout flow.\n\n**API Changes**\n\`POST /v2/payments/quick-checkout\`\n\`GET /v2/payments/methods/:userId\`\n\n**Data Models**\n- SavedMethod: { id, last4, brand, expiry }\n- QuickCheckout: { userId, amount, methodId }\n\n**Open Questions**\n- Risk scoring threshold for 3DS bypass\n- Idempotency key strategy`,
        actions: ["View in Notion", "Generate Tests", "Generate Collection"],
      },
      {
        id: "tests-1", type: "tests", label: "Test Cases", title: "5 cases · 3 passing",
        state: "partial", connector: "GitHub CI", connectorColor: "#6e7681",
        stats: "3 / 5",
        detail: `**TC-001** ✅ Happy path quick checkout\n**TC-002** ✅ Invalid card returns 422\n**TC-003** ✅ Idempotent duplicate request\n**TC-004** ❌ High-value 3DS bypass (failing)\n**TC-005** ❌ Expired card handling (failing)\n\n*2 test cases generated by AI, 1 human-written*`,
        actions: ["View in GitHub", "Run All", "Generate More"],
      },
      {
        id: "col-1", type: "collection", label: "API Collection", title: "payments-v2.restol",
        state: "running", connector: "Restol", connectorColor: "#10b981",
        stats: "8 requests",
        detail: `**Collection**: payments-v2\n**Environment**: staging\n**Last run**: 2 min ago · 6/8 passing\n\nPOST /v2/payments/quick-checkout ✅\nGET  /v2/payments/methods/:id ✅\nPOST /v2/payments (legacy) ✅\nDELETE /v2/payments/:id ✅\nPOST /v2/payments/refund ✅\nGET  /v2/payments/status ✅\nPOST /v2/payments/quick-checkout (high-value) ❌\nGET  /v2/payments/methods (empty) ❌`,
        actions: ["Run Collection", "View Results", "Export k6"],
      },
      {
        id: "dep-1", type: "deploy", label: "Deployment", title: "v2.3.0 · staging",
        state: "pending", connector: "ArgoCD", connectorColor: "#f97316",
        detail: `**Version**: payments-service v2.3.0\n**Environment**: staging\n**Status**: Blocked — 2 test cases failing\n**Cluster**: eks-us-east-1\n**Namespace**: payments\n\n*Deploy to prod gated on all tests passing*\n\nRecent deploys:\n- v2.2.9 → prod · 3 days ago ✅\n- v2.2.8 → prod · 8 days ago ✅`,
        actions: ["View in ArgoCD", "View Manifest", "Force Deploy"],
      },
      {
        id: "met-1", type: "metrics", label: "Metrics", title: "Not yet deployed",
        state: "inactive", connector: "Datadog", connectorColor: "#7c3aed",
        detail: `**Dashboard**: payments-v2-prod\n**Status**: Awaiting deployment\n\nWill monitor:\n- Checkout completion rate\n- p99 latency /v2/payments\n- Error rate by endpoint\n- 3DS bypass rate\n\n*Linked to PRD success metrics*`,
        actions: ["Preview Dashboard", "Configure Alerts"],
      },
    ],
  },
  {
    id: "feat-2",
    name: "Payment Method Management",
    team: "Payments",
    stages: [
      {
        id: "prd-2", type: "prd", label: "PRD", title: "Saved Payment Methods UI",
        state: "approved", connector: "Linear", connectorColor: "#5e6ad2",
        detail: "Allow users to manage their saved cards from account settings.",
        actions: ["View in Linear", "Generate Spec"],
      },
      {
        id: "spec-2", type: "spec", label: "Tech Spec", title: "Methods API + UI",
        state: "review", connector: "Notion", connectorColor: "#ffffff",
        detail: "In review with team lead. Covers CRUD endpoints for payment methods.",
        actions: ["View in Notion", "Generate Tests"],
      },
      {
        id: "tests-2", type: "tests", label: "Test Cases", title: "Not generated",
        state: "pending", connector: "—", connectorColor: "#555",
        detail: "Waiting for spec approval before generating test cases.",
        actions: ["Generate Tests"],
      },
      {
        id: "col-2", type: "collection", label: "API Collection", title: "Not created",
        state: "inactive", connector: "—", connectorColor: "#555",
        detail: "Will be auto-generated from spec.",
        actions: ["Generate Collection"],
      },
      {
        id: "dep-2", type: "deploy", label: "Deployment", title: "—",
        state: "inactive", connector: "ArgoCD", connectorColor: "#f97316",
        detail: "No deployment yet.",
        actions: [],
      },
      {
        id: "met-2", type: "metrics", label: "Metrics", title: "—",
        state: "inactive", connector: "Datadog", connectorColor: "#7c3aed",
        detail: "No metrics configured.",
        actions: [],
      },
    ],
  },
];

export interface Connector {
  id: string;
  name: string;
  category: string;
  description: string;
  connected: boolean;
  lastSync?: string;
  color: string;
  icon: string;
  capabilities: string[];
  configFields: { label: string; key: string; type: string }[];
}

export const CONNECTORS: Connector[] = [
  { id: "github", name: "GitHub", category: "Code & CI", description: "Repos, PRs, Actions, Issues", connected: true, lastSync: "2 min ago", color: "#6e7681", icon: "GH", capabilities: ["code", "ci", "issues"], configFields: [{ label: "Personal Access Token", key: "token", type: "password" }, { label: "Organization", key: "org", type: "text" }] },
  { id: "linear", name: "Linear", category: "Issue Tracking", description: "Issues, projects, cycles", connected: true, lastSync: "5 min ago", color: "#5e6ad2", icon: "LN", capabilities: ["issues", "roadmap"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "Team ID", key: "team_id", type: "text" }] },
  { id: "datadog", name: "Datadog", category: "Observability", description: "Metrics, APM, logs, dashboards", connected: true, lastSync: "1 min ago", color: "#7c3aed", icon: "DD", capabilities: ["metrics", "logs", "traces", "alerts"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "App Key", key: "app_key", type: "password" }] },
  { id: "argocd", name: "ArgoCD", category: "Deployment", description: "GitOps deployments, rollbacks", connected: true, lastSync: "3 min ago", color: "#f97316", icon: "AC", capabilities: ["deployments", "rollbacks"], configFields: [{ label: "Server URL", key: "server", type: "text" }, { label: "Auth Token", key: "token", type: "password" }] },
  { id: "coralogix", name: "Coralogix", category: "Logging", description: "Log management and analysis", connected: true, lastSync: "30 sec ago", color: "#06b6d4", icon: "CX", capabilities: ["logs", "alerts"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "Region", key: "region", type: "text" }] },
  { id: "notion", name: "Notion", category: "Docs", description: "Specs, runbooks, wikis", connected: true, lastSync: "15 min ago", color: "#e5e5e5", icon: "NT", capabilities: ["docs"], configFields: [{ label: "Integration Token", key: "token", type: "password" }, { label: "Database ID", key: "database_id", type: "text" }] },
  { id: "eks", name: "Amazon EKS", category: "Kubernetes", description: "Clusters, pods, services, metrics", connected: true, lastSync: "1 min ago", color: "#f59e0b", icon: "EK", capabilities: ["k8s", "infrastructure"], configFields: [{ label: "Cluster Name", key: "cluster", type: "text" }, { label: "Region", key: "region", type: "text" }, { label: "Kubeconfig", key: "kubeconfig", type: "textarea" }] },
  { id: "prometheus", name: "Prometheus", category: "Observability", description: "Self-hosted metrics and alerting", connected: false, color: "#e55b2e", icon: "PR", capabilities: ["metrics", "alerts"], configFields: [{ label: "Endpoint URL", key: "url", type: "text" }, { label: "Basic Auth User", key: "user", type: "text" }, { label: "Basic Auth Password", key: "password", type: "password" }] },
  { id: "newrelic", name: "New Relic", category: "Observability", description: "APM, metrics, browser monitoring", connected: false, color: "#1ce783", icon: "NR", capabilities: ["metrics", "logs", "traces"], configFields: [{ label: "License Key", key: "license_key", type: "password" }, { label: "Account ID", key: "account_id", type: "text" }] },
  { id: "jira", name: "Jira", category: "Issue Tracking", description: "Issues, sprints, epics", connected: false, color: "#0052cc", icon: "JR", capabilities: ["issues", "roadmap"], configFields: [{ label: "Site URL", key: "site", type: "text" }, { label: "API Token", key: "token", type: "password" }, { label: "Email", key: "email", type: "text" }] },
  { id: "loki", name: "Loki", category: "Logging", description: "Log aggregation (Grafana stack)", connected: false, color: "#f9a825", icon: "LK", capabilities: ["logs"], configFields: [{ label: "Endpoint URL", key: "url", type: "text" }, { label: "Org ID", key: "org_id", type: "text" }] },
  { id: "terraform", name: "Terraform Cloud", category: "Infrastructure", description: "IaC runs, state, workspaces", connected: false, color: "#7b42bc", icon: "TF", capabilities: ["infrastructure"], configFields: [{ label: "API Token", key: "token", type: "password" }, { label: "Organization", key: "org", type: "text" }] },
  { id: "pagerduty", name: "PagerDuty", category: "Alerting", description: "Incidents, on-call schedules", connected: false, color: "#06a94d", icon: "PD", capabilities: ["alerts", "incidents"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "Service ID", key: "service_id", type: "text" }] },
  { id: "gke", name: "Google GKE", category: "Kubernetes", description: "GCP managed Kubernetes", connected: false, color: "#4285f4", icon: "GK", capabilities: ["k8s", "infrastructure"], configFields: [{ label: "Project ID", key: "project_id", type: "text" }, { label: "Cluster Name", key: "cluster", type: "text" }, { label: "Service Account JSON", key: "sa_json", type: "textarea" }] },
];

export const AI_RESPONSES: Record<string, string[]> = {
  "Generate Spec": [
    "Reading PRD: Reduce Checkout Friction...\n",
    "Analyzing success metrics and feature scope...\n",
    "Identifying API surface changes needed...\n\n",
    "**Technical Specification: Payment API v2**\n\n",
    "## Architecture Decision\n",
    "Extend `payment-service` with a dedicated quick-checkout path. Avoids breaking changes to v1 endpoints.\n\n",
    "## New Endpoints\n",
    "```\nPOST /v2/payments/quick-checkout\n  body: { userId, amount, methodId }\n  returns: { paymentId, status, requiresAction? }\n```\n\n",
    "## Risk Scoring Integration\n",
    "Call `risk-service` synchronously. If score < 0.3 and amount < $50, skip 3DS. Else fall through to standard flow.\n\n",
    "## Data Model Changes\n",
    "Add `risk_score` and `quick_checkout` flag to `Payment` table. Migration: non-breaking, nullable columns.\n\n",
    "**3 open questions added for team review →**",
  ],
  "Generate Tests": [
    "Reading spec: Payment API v2 Refactor...\n",
    "Extracting API contracts and edge cases...\n\n",
    "**Generating test cases**\n\n",
    "TC-001: Happy path — quick checkout, low-value, no 3DS ✓\n",
    "TC-002: Invalid payment method returns 422 ✓\n",
    "TC-003: Idempotent duplicate request returns same paymentId ✓\n",
    "TC-004: High-value transaction triggers 3DS ✓\n",
    "TC-005: Expired card returns 402 ✓\n",
    "TC-006: Risk score threshold boundary (edge case) ✓\n",
    "TC-007: Concurrent requests with same idempotency key ✓\n\n",
    "**7 test cases created → pushed to GitHub as draft PR**",
  ],
  "Generate Collection": [
    "Reading spec contracts...\n",
    "Parsing endpoint schemas...\n\n",
    "Building collection: payments-v2.restol.yaml\n\n",
    "  POST /v2/payments/quick-checkout — with body + assertions\n",
    "  GET  /v2/payments/methods/:userId — parameterized\n",
    "  POST /v2/payments/quick-checkout (high-value) — edge case\n",
    "  POST /v2/payments/quick-checkout (invalid method) — negative\n",
    "  POST /v2/payments/quick-checkout (duplicate idempotency) — replay\n\n",
    "**Collection saved · 5 requests · ready to run against staging**",
  ],
  "default": [
    "Analyzing context...\n\n",
    "Reading connected sources: Linear, Notion, GitHub CI...\n\n",
    "**Summary**\n\n",
    "Feature is at 60% completion. 2 test cases blocking deployment.\n\n",
    "Recommended next action: fix TC-004 (high-value 3DS) — the spec\nhas a gap in the risk score threshold definition.\n\n",
    "**Ask me**: 'Why is TC-004 failing?' or 'Trace this to the PRD'",
  ],
};

// ─── Audit types ────────────────────────────────────────────────────────────

export type AuditOutcome =
  | "root_cause_found"
  | "answer_provided"
  | "status_provided"
  | "analysis_provided"
  | "gate_required"
  | "pr_created"
  | "access_denied"
  | "auto_approved"
  | "rollback_initiated"
  | "blocked";

export interface AuditEvent {
  id: string;
  timestamp: string;
  user: string;
  authRole: string;
  inferredRole: string;
  query: string;
  agents: string[];
  outcome: AuditOutcome;
  detail: string;
  durationMs: number;
}

export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "evt-001",
    timestamp: "2026-05-31 14:47:02",
    user: "alice",
    authRole: "dev",
    inferredRole: "sre",
    query: "Alert: payments-api error rate 8%",
    agents: ["datadog-agent", "loki-agent", "k8s-agent", "github-agent"],
    outcome: "root_cause_found",
    detail: "Root cause identified: payments-service v2.3.0 deployed 14 min ago introduced null pointer in QuickCheckoutHandler.java:89. Confidence: 0.94.",
    durationMs: 3240,
  },
  {
    id: "evt-002",
    timestamp: "2026-05-31 14:48:15",
    user: "alice",
    authRole: "dev",
    inferredRole: "sre",
    query: "Rollback to v2.2.9",
    agents: ["argocd-agent"],
    outcome: "gate_required",
    detail: "Rollback action requires L2 approval gate. Waiting for tech-lead sign-off. Gate ID: gate-prod-rollback-881.",
    durationMs: 820,
  },
  {
    id: "evt-003",
    timestamp: "2026-05-31 14:49:30",
    user: "alice",
    authRole: "dev",
    inferredRole: "sre",
    query: "Page on-call lead",
    agents: ["pagerduty-agent"],
    outcome: "answer_provided",
    detail: "PagerDuty incident P-4421 created and assigned to on-call engineer (bob). Escalation policy triggered.",
    durationMs: 610,
  },
  {
    id: "evt-004",
    timestamp: "2026-05-31 14:52:10",
    user: "bob",
    authRole: "dev",
    inferredRole: "dev",
    query: "Why is TC-005 failing?",
    agents: ["github-agent", "test-agent", "repo-agent"],
    outcome: "answer_provided",
    detail: "TC-005 fails due to missing idempotency lock in checkout.ts:14. Two concurrent requests create duplicate payments. Fix: add idempotencyKey check before DB insert.",
    durationMs: 2100,
  },
  {
    id: "evt-005",
    timestamp: "2026-05-31 14:53:44",
    user: "bob",
    authRole: "dev",
    inferredRole: "dev",
    query: "Write the fix for TC-005",
    agents: ["repo-agent"],
    outcome: "pr_created",
    detail: "PR #342 created on org/payments-service: 'fix: add idempotency lock to quick-checkout handler'. Branch: fix/idempotency-tc005.",
    durationMs: 4500,
  },
  {
    id: "evt-006",
    timestamp: "2026-05-31 14:55:00",
    user: "carol",
    authRole: "pm",
    inferredRole: "pm",
    query: "Status of Reduce Checkout Friction",
    agents: ["linear-agent", "github-agent", "argocd-agent", "datadog-agent"],
    outcome: "status_provided",
    detail: "Feature 65% complete. TC-004 and TC-005 failing. Deploy blocked. Estimated 2-day slip from original 2-week target.",
    durationMs: 1870,
  },
  {
    id: "evt-007",
    timestamp: "2026-05-31 14:57:22",
    user: "carol",
    authRole: "pm",
    inferredRole: "pm",
    query: "Notify stakeholders of 2-day slip",
    agents: ["linear-agent"],
    outcome: "answer_provided",
    detail: "Linear update posted to team-payments channel. Status set to 'At Risk'. 3 stakeholders notified via Linear notification.",
    durationMs: 950,
  },
  {
    id: "evt-008",
    timestamp: "2026-05-31 15:01:05",
    user: "david",
    authRole: "ba",
    inferredRole: "ba",
    query: "Checkout user journey this week",
    agents: ["datadog-agent", "linear-agent", "github-agent"],
    outcome: "analysis_provided",
    detail: "Overall conversion 31.4% (↑ from 28.1%). Biggest drop: cart→checkout 28% on mobile. Payment entry drop 40% linked to 3DS on $30–$50 range.",
    durationMs: 2880,
  },
  {
    id: "evt-009",
    timestamp: "2026-05-31 15:03:18",
    user: "alice",
    authRole: "dev",
    inferredRole: "dev",
    query: "Show prod db credentials",
    agents: [],
    outcome: "access_denied",
    detail: "ACCESS DENIED — 'prod db credentials' is outside alice's permission perimeter. Connector: rds-prod. Required scope: db:secrets:read. alice's envelope: [github:read, datadog:read, loki:read, k8s:app-ns:read].",
    durationMs: 45,
  },
  {
    id: "evt-010",
    timestamp: "2026-05-31 15:05:44",
    user: "system",
    authRole: "system",
    inferredRole: "system",
    query: "Deploy gate evaluation: catalog-service v1.9.2 → staging",
    agents: ["argocd-agent", "test-agent"],
    outcome: "auto_approved",
    detail: "Auto-approved: all 7 tests passing, confidence 0.95. Service policy: L3 Supervise. Gate type: auto (confidence ≥ 0.90). Deploy initiated.",
    durationMs: 1200,
  },
  {
    id: "evt-011",
    timestamp: "2026-05-31 15:08:30",
    user: "eve",
    authRole: "sre",
    inferredRole: "sre",
    query: "Show all pods in CrashLoopBackOff across clusters",
    agents: ["k8s-agent"],
    outcome: "answer_provided",
    detail: "3 pods in CrashLoopBackOff: payments-api-7d9f-x2k (payments ns), payments-api-7d9f-p4m (payments ns), payments-api-7d9f-r8q (payments ns). All on v2.3.0.",
    durationMs: 1540,
  },
  {
    id: "evt-012",
    timestamp: "2026-05-31 15:09:55",
    user: "eve",
    authRole: "sre",
    inferredRole: "sre",
    query: "Scale healthy pods to 5 replicas in payments namespace",
    agents: ["k8s-agent"],
    outcome: "gate_required",
    detail: "Scale action requires L2 approval. Gate ID: gate-k8s-scale-992. Waiting for tech-lead. Auto-approve threshold: confidence ≥ 0.90 (current: 0.87).",
    durationMs: 670,
  },
  {
    id: "evt-013",
    timestamp: "2026-05-31 15:11:10",
    user: "bob",
    authRole: "dev",
    inferredRole: "dev",
    query: "Create regression test for TC-005 fix",
    agents: ["test-agent", "repo-agent"],
    outcome: "pr_created",
    detail: "TC-008 added to test suite: 'Concurrent checkout requests return same paymentId'. Added to existing PR #342.",
    durationMs: 3200,
  },
  {
    id: "evt-014",
    timestamp: "2026-05-31 15:14:00",
    user: "carol",
    authRole: "pm",
    inferredRole: "ba",
    query: "Export checkout funnel analysis to Linear",
    agents: ["linear-agent", "datadog-agent"],
    outcome: "answer_provided",
    detail: "Linear issue LIN-2291 created with funnel analysis attachment. Linked to epic: Reduce Checkout Friction.",
    durationMs: 1100,
  },
  {
    id: "evt-015",
    timestamp: "2026-05-31 15:16:45",
    user: "alice",
    authRole: "dev",
    inferredRole: "sre",
    query: "Rollback payments-api to v2.2.9 — approved by tech-lead",
    agents: ["argocd-agent", "k8s-agent"],
    outcome: "rollback_initiated",
    detail: "Gate gate-prod-rollback-881 approved by @priya (tech-lead). ArgoCD rollback initiated: payments-service v2.3.0 → v2.2.9. ETA: 90 seconds.",
    durationMs: 2300,
  },
  {
    id: "evt-016",
    timestamp: "2026-05-31 15:18:20",
    user: "david",
    authRole: "ba",
    inferredRole: "ba",
    query: "Compare checkout conversion to last month",
    agents: ["datadog-agent"],
    outcome: "analysis_provided",
    detail: "May 2026: 31.4% conversion. April 2026: 26.8% conversion. Delta: +4.6pp. Primary driver: mobile friction improvements in Apr 28 deploy.",
    durationMs: 2050,
  },
  {
    id: "evt-017",
    timestamp: "2026-05-31 15:20:00",
    user: "eve",
    authRole: "sre",
    inferredRole: "sre",
    query: "Check Loki logs for NullPointerException in payments",
    agents: ["loki-agent"],
    outcome: "answer_provided",
    detail: "47 NullPointerException events in last 30 min. All from QuickCheckoutHandler.java:89. First occurrence: 14:33:02 (1 min after v2.3.0 deploy).",
    durationMs: 1380,
  },
  {
    id: "evt-018",
    timestamp: "2026-05-31 15:22:15",
    user: "system",
    authRole: "system",
    inferredRole: "system",
    query: "Payments-api rollback health check",
    agents: ["datadog-agent", "k8s-agent"],
    outcome: "answer_provided",
    detail: "Rollback complete. payments-api v2.2.9 running 5/5 pods healthy. Error rate: 0.1% (normal baseline). p99 latency: 142ms.",
    durationMs: 890,
  },
];

// ─── Access control types ───────────────────────────────────────────────────

export interface ConnectorAccess {
  connectorId: string;
  connectorName: string;
  icon: string;
  color: string;
  mode: "read" | "read-write" | "none";
  readScope: string[];
  writeScope: string[];
  status: "active" | "limited" | "disabled";
}

export interface UserAccess {
  id: string;
  name: string;
  email: string;
  authRole: "dev" | "pm" | "sre" | "ba" | "admin";
  connectors: ConnectorAccess[];
}

export interface ConnectorManifest {
  connectorId: string;
  connectorName: string;
  icon: string;
  color: string;
  capabilities: {
    read: string[];
    write: string[];
  };
}

export const CONNECTOR_MANIFESTS: ConnectorManifest[] = [
  {
    connectorId: "k8s-prod",
    connectorName: "Amazon EKS (prod)",
    icon: "EK",
    color: "#f59e0b",
    capabilities: {
      read: ["*"],
      write: ["deployments/payments-api", "deployments/catalog-service", "deployments/auth-service"],
    },
  },
  {
    connectorId: "github",
    connectorName: "GitHub",
    icon: "GH",
    color: "#6e7681",
    capabilities: {
      read: ["org/*"],
      write: ["org/payments-service", "org/catalog-service", "org/auth-service"],
    },
  },
  {
    connectorId: "linear",
    connectorName: "Linear",
    icon: "LN",
    color: "#5e6ad2",
    capabilities: {
      read: ["team-payments/*", "team-platform/*"],
      write: ["team-payments/issues", "team-payments/projects"],
    },
  },
  {
    connectorId: "datadog",
    connectorName: "Datadog",
    icon: "DD",
    color: "#7c3aed",
    capabilities: {
      read: ["*"],
      write: [],
    },
  },
  {
    connectorId: "argocd",
    connectorName: "ArgoCD",
    icon: "AC",
    color: "#f97316",
    capabilities: {
      read: ["*"],
      write: ["apps/payments-api", "apps/catalog-service"],
    },
  },
  {
    connectorId: "loki",
    connectorName: "Loki",
    icon: "LK",
    color: "#f9a825",
    capabilities: {
      read: ["*"],
      write: [],
    },
  },
];

export const USERS: UserAccess[] = [
  {
    id: "alice",
    name: "Alice Chen",
    email: "alice@acme.dev",
    authRole: "dev",
    connectors: [
      { connectorId: "github", connectorName: "GitHub", icon: "GH", color: "#6e7681", mode: "read-write", readScope: ["org/*"], writeScope: ["org/payments-service", "org/catalog-service"], status: "active" },
      { connectorId: "datadog", connectorName: "Datadog", icon: "DD", color: "#7c3aed", mode: "read", readScope: ["*"], writeScope: [], status: "active" },
      { connectorId: "loki", connectorName: "Loki", icon: "LK", color: "#f9a825", mode: "read", readScope: ["namespace/payments", "namespace/catalog"], writeScope: [], status: "active" },
      { connectorId: "k8s-prod", connectorName: "Amazon EKS (prod)", icon: "EK", color: "#f59e0b", mode: "read", readScope: ["namespace/payments", "namespace/catalog"], writeScope: [], status: "limited" },
      { connectorId: "linear", connectorName: "Linear", icon: "LN", color: "#5e6ad2", mode: "read", readScope: ["team-payments/*"], writeScope: [], status: "active" },
      { connectorId: "argocd", connectorName: "ArgoCD", icon: "AC", color: "#f97316", mode: "none", readScope: [], writeScope: [], status: "disabled" },
    ],
  },
  {
    id: "bob",
    name: "Bob Tran",
    email: "bob@acme.dev",
    authRole: "dev",
    connectors: [
      { connectorId: "github", connectorName: "GitHub", icon: "GH", color: "#6e7681", mode: "read-write", readScope: ["org/*"], writeScope: ["org/payments-service"], status: "active" },
      { connectorId: "datadog", connectorName: "Datadog", icon: "DD", color: "#7c3aed", mode: "read", readScope: ["service/payments-api"], writeScope: [], status: "active" },
      { connectorId: "loki", connectorName: "Loki", icon: "LK", color: "#f9a825", mode: "read", readScope: ["namespace/payments"], writeScope: [], status: "active" },
      { connectorId: "k8s-prod", connectorName: "Amazon EKS (prod)", icon: "EK", color: "#f59e0b", mode: "none", readScope: [], writeScope: [], status: "disabled" },
      { connectorId: "linear", connectorName: "Linear", icon: "LN", color: "#5e6ad2", mode: "read", readScope: ["team-payments/*"], writeScope: [], status: "active" },
      { connectorId: "argocd", connectorName: "ArgoCD", icon: "AC", color: "#f97316", mode: "none", readScope: [], writeScope: [], status: "disabled" },
    ],
  },
  {
    id: "carol",
    name: "Carol Park",
    email: "carol@acme.dev",
    authRole: "pm",
    connectors: [
      { connectorId: "github", connectorName: "GitHub", icon: "GH", color: "#6e7681", mode: "read", readScope: ["org/*"], writeScope: [], status: "active" },
      { connectorId: "datadog", connectorName: "Datadog", icon: "DD", color: "#7c3aed", mode: "read", readScope: ["dashboard/*"], writeScope: [], status: "active" },
      { connectorId: "loki", connectorName: "Loki", icon: "LK", color: "#f9a825", mode: "none", readScope: [], writeScope: [], status: "disabled" },
      { connectorId: "k8s-prod", connectorName: "Amazon EKS (prod)", icon: "EK", color: "#f59e0b", mode: "none", readScope: [], writeScope: [], status: "disabled" },
      { connectorId: "linear", connectorName: "Linear", icon: "LN", color: "#5e6ad2", mode: "read-write", readScope: ["team-payments/*", "team-platform/*"], writeScope: ["team-payments/issues", "team-payments/projects"], status: "active" },
      { connectorId: "argocd", connectorName: "ArgoCD", icon: "AC", color: "#f97316", mode: "none", readScope: [], writeScope: [], status: "disabled" },
    ],
  },
  {
    id: "david",
    name: "David Kim",
    email: "david@acme.dev",
    authRole: "ba",
    connectors: [
      { connectorId: "github", connectorName: "GitHub", icon: "GH", color: "#6e7681", mode: "read", readScope: ["org/*/metrics"], writeScope: [], status: "active" },
      { connectorId: "datadog", connectorName: "Datadog", icon: "DD", color: "#7c3aed", mode: "read", readScope: ["*"], writeScope: [], status: "active" },
      { connectorId: "loki", connectorName: "Loki", icon: "LK", color: "#f9a825", mode: "none", readScope: [], writeScope: [], status: "disabled" },
      { connectorId: "k8s-prod", connectorName: "Amazon EKS (prod)", icon: "EK", color: "#f59e0b", mode: "none", readScope: [], writeScope: [], status: "disabled" },
      { connectorId: "linear", connectorName: "Linear", icon: "LN", color: "#5e6ad2", mode: "read", readScope: ["team-payments/*"], writeScope: [], status: "active" },
      { connectorId: "argocd", connectorName: "ArgoCD", icon: "AC", color: "#f97316", mode: "none", readScope: [], writeScope: [], status: "disabled" },
    ],
  },
  {
    id: "eve",
    name: "Eve Okonkwo",
    email: "eve@acme.dev",
    authRole: "sre",
    connectors: [
      { connectorId: "github", connectorName: "GitHub", icon: "GH", color: "#6e7681", mode: "read", readScope: ["org/*"], writeScope: [], status: "active" },
      { connectorId: "datadog", connectorName: "Datadog", icon: "DD", color: "#7c3aed", mode: "read", readScope: ["*"], writeScope: [], status: "active" },
      { connectorId: "loki", connectorName: "Loki", icon: "LK", color: "#f9a825", mode: "read", readScope: ["*"], writeScope: [], status: "active" },
      { connectorId: "k8s-prod", connectorName: "Amazon EKS (prod)", icon: "EK", color: "#f59e0b", mode: "read-write", readScope: ["*"], writeScope: ["deployments/payments-api", "deployments/catalog-service"], status: "active" },
      { connectorId: "linear", connectorName: "Linear", icon: "LN", color: "#5e6ad2", mode: "read", readScope: ["team-payments/*"], writeScope: [], status: "active" },
      { connectorId: "argocd", connectorName: "ArgoCD", icon: "AC", color: "#f97316", mode: "read-write", readScope: ["*"], writeScope: ["apps/payments-api", "apps/catalog-service"], status: "active" },
    ],
  },
];

// ─── Workflow types ─────────────────────────────────────────────────────────

export type GateType = "manual" | "auto" | "disabled";
export type AutonomyLevel = "L1" | "L2" | "L3" | "L4";

export interface GateConfig {
  type: GateType;
  requiredApprovals: number;
  autoApproveConfidence: number;
  requiredApprovers: string[];
}

export interface WorkflowStage {
  id: string;
  name: string;
  icon: string;
  description: string;
  gate: GateConfig;
  agents: string[];
}

export interface ServicePolicy {
  id: string;
  name: string;
  autonomyLevel: AutonomyLevel;
  description: string;
}

export const WORKFLOW_STAGES: WorkflowStage[] = [
  {
    id: "prd",
    name: "PRD",
    icon: "📄",
    description: "Product requirement document approved by PM",
    gate: { type: "manual", requiredApprovals: 1, autoApproveConfidence: 0.95, requiredApprovers: ["pm"] },
    agents: ["linear-agent"],
  },
  {
    id: "spec",
    name: "Tech Spec",
    icon: "📐",
    description: "Technical specification reviewed by tech lead",
    gate: { type: "manual", requiredApprovals: 2, autoApproveConfidence: 0.92, requiredApprovers: ["tech-lead", "pm"] },
    agents: ["github-agent", "repo-agent"],
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    icon: "⚡",
    description: "Project scaffolding and initial setup",
    gate: { type: "auto", requiredApprovals: 1, autoApproveConfidence: 0.90, requiredApprovers: ["tech-lead"] },
    agents: ["repo-agent"],
  },
  {
    id: "tests",
    name: "Tests",
    icon: "🧪",
    description: "All test cases must pass before proceeding",
    gate: { type: "auto", requiredApprovals: 1, autoApproveConfidence: 0.90, requiredApprovers: ["tech-lead"] },
    agents: ["test-agent", "github-agent"],
  },
  {
    id: "pr",
    name: "PR Review",
    icon: "🔍",
    description: "Code review by at least one peer",
    gate: { type: "manual", requiredApprovals: 2, autoApproveConfidence: 0.95, requiredApprovers: ["tech-lead", "peer"] },
    agents: ["github-agent", "repo-agent"],
  },
  {
    id: "deploy",
    name: "Deploy",
    icon: "🚀",
    description: "Deploy to staging then production",
    gate: { type: "manual", requiredApprovals: 2, autoApproveConfidence: 0.95, requiredApprovers: ["tech-lead", "sre"] },
    agents: ["argocd-agent", "k8s-agent"],
  },
  {
    id: "monitor",
    name: "Monitor",
    icon: "📊",
    description: "Continuous observability post-deploy",
    gate: { type: "disabled", requiredApprovals: 0, autoApproveConfidence: 0.90, requiredApprovers: [] },
    agents: ["datadog-agent", "loki-agent", "k8s-agent"],
  },
];

export const SERVICE_POLICIES: ServicePolicy[] = [
  { id: "payments-api", name: "payments-api", autonomyLevel: "L2", description: "High-value service. Agent can analyze and recommend; all actions require approval." },
  { id: "catalog-service", name: "catalog-service", autonomyLevel: "L3", description: "Medium-risk. Agent can execute non-destructive actions; destructive actions supervised." },
  { id: "auth-service", name: "auth-service", autonomyLevel: "L2", description: "Security-critical. Agent can analyze only; all changes require human approval." },
];

// ─── Orchestrator scenarios ─────────────────────────────────────────────────

export interface AgentActivity {
  id: string;
  name: string;
  status: "pending" | "running" | "done" | "error";
  detail: string;
  startDelay: number;
  duration: number;
}

export interface OrchestratorScenario {
  id: string;
  label: string;
  emoji: string;
  query: string;
  authRole: string;
  inferredRole: string;
  agents: AgentActivity[];
  response: string;
  followUps: string[];
}

export const SCENARIOS: OrchestratorScenario[] = [
  {
    id: "sre-alert",
    label: "Alert: payments-api error rate 8%",
    emoji: "🔴",
    query: "Alert: payments-api error rate 8%",
    authRole: "dev",
    inferredRole: "sre",
    agents: [
      { id: "datadog-agent", name: "datadog-agent", status: "pending", detail: "Fetching error rate metrics and APM traces", startDelay: 300, duration: 1800 },
      { id: "loki-agent", name: "loki-agent", status: "pending", detail: "Scanning logs for exception patterns", startDelay: 500, duration: 2200 },
      { id: "k8s-agent", name: "k8s-agent", status: "pending", detail: "Checking pod health and recent restarts", startDelay: 800, duration: 1500 },
      { id: "github-agent", name: "github-agent", status: "pending", detail: "Cross-referencing recent commits and deploys", startDelay: 1200, duration: 2000 },
    ],
    response: "**Root cause identified.** payments-api v2.3.0 deployed 14 min ago. Error spike started at deploy time.\n\n**Trail:**\n→ ArgoCD deployed payments-service v2.3.0 at 14:32\n→ Loki: NullPointerException in `QuickCheckoutHandler.java:89` — `riskScore` field null when `amount > 500`\n→ K8s: 3/5 pods in CrashLoopBackOff, 2 healthy pods absorbing load\n→ GitHub: commit `a4f21bc` removed null check in risk scoring path\n\n**Confidence:** 0.94 — root cause is the missing null check\n\n**Recommended action:** rollback to v2.2.9 or hotfix line 89",
    followUps: ["Rollback to v2.2.9", "Create hotfix PR", "Page on-call lead"],
  },
  {
    id: "pm-status",
    label: "Status of Reduce Checkout Friction",
    emoji: "📋",
    query: "Status of Reduce Checkout Friction",
    authRole: "pm",
    inferredRole: "pm",
    agents: [
      { id: "linear-agent", name: "linear-agent", status: "pending", detail: "Fetching feature status and milestone data", startDelay: 200, duration: 1400 },
      { id: "github-agent", name: "github-agent", status: "pending", detail: "Reading CI test results and PR status", startDelay: 400, duration: 1800 },
      { id: "argocd-agent", name: "argocd-agent", status: "pending", detail: "Checking deployment gate status", startDelay: 700, duration: 1200 },
      { id: "datadog-agent", name: "datadog-agent", status: "pending", detail: "Pulling production readiness metrics", startDelay: 1000, duration: 1600 },
    ],
    response: "**Reduce Checkout Friction — 65% complete**\n\n**Current state:** Tests (partial) — 3/5 passing\n**Blocker:** TC-004 (high-value 3DS bypass) and TC-005 (concurrent requests) failing\n**Next gate:** All 5 tests must pass before staging deploy\n\n**Timeline:**\n→ PRD approved 8 days ago ✓\n→ Tech spec in review (2 reviewers pending) ⏳\n→ 3 of 5 tests passing ⚠\n→ Deploy blocked — estimated 2 days to unblock\n\n**At risk:** original 2-week target. Current pace suggests 3 days slip.",
    followUps: ["Show blocking tests", "Notify stakeholders", "Generate status report"],
  },
  {
    id: "dev-debug",
    label: "Why is TC-005 failing?",
    emoji: "🔍",
    query: "Why is TC-005 failing?",
    authRole: "dev",
    inferredRole: "dev",
    agents: [
      { id: "github-agent", name: "github-agent", status: "pending", detail: "Reading test case definition and CI logs", startDelay: 200, duration: 1600 },
      { id: "test-agent", name: "test-agent", status: "pending", detail: "Analyzing test failure trace", startDelay: 500, duration: 2000 },
      { id: "repo-agent", name: "repo-agent", status: "pending", detail: "Reading checkout.ts source code", startDelay: 900, duration: 1400 },
    ],
    response: "**TC-005 fails due to missing idempotency lock.**\n\n**Trace:**\n→ TC-005 sends 2 concurrent POST /v2/payments/quick-checkout with same body\n→ Both requests pass the method ownership check (line 9)\n→ Both reach `paymentService.create()` simultaneously (line 14)\n→ No idempotency lock before DB insert → 2 payments created\n→ Test expects same `paymentId` returned — gets two different IDs\n\n**Root cause:** `checkout.ts:14` — `paymentService.create()` called without checking for existing in-flight payment with same idempotency key\n\n**Fix:** Add idempotency check before line 14:\n```\nconst existing = await db.payments.findByIdempotencyKey(req.idempotencyKey)\nif (existing) return res.json(existing)\n```",
    followUps: ["Write the fix", "Create regression test", "Check other endpoints"],
  },
  {
    id: "ba-analysis",
    label: "Checkout user journey this week",
    emoji: "📊",
    query: "Checkout user journey this week",
    authRole: "ba",
    inferredRole: "ba",
    agents: [
      { id: "datadog-agent", name: "datadog-agent", status: "pending", detail: "Pulling funnel metrics from RUM dashboards", startDelay: 200, duration: 2200 },
      { id: "linear-agent", name: "linear-agent", status: "pending", detail: "Correlating with active feature flags", startDelay: 600, duration: 1400 },
      { id: "github-agent", name: "github-agent", status: "pending", detail: "Checking deployed feature versions", startDelay: 900, duration: 1200 },
    ],
    response: "**Checkout user journey — this week**\n\n**Funnel (Mon–Sun):**\n→ Add to cart: 12,400 sessions\n→ Checkout initiated: 8,920 (72%)\n→ Payment entered: 5,340 (60% of initiated)\n→ Payment completed: 3,890 (73% of entered)\n→ **Overall conversion: 31.4%** ↑ from 28.1% last week\n\n**Drop-off analysis:**\n→ Biggest drop: cart → checkout (28%) — mobile users, form friction\n→ Payment entry drop (40%) — 3DS prompt causing abandonment on $30–$50 range\n\n**Correlates with:** Reduce Checkout Friction feature currently in test phase — not yet deployed",
    followUps: ["Export to Linear", "Compare to last month", "Identify highest-value drop-off"],
  },
];
