export type StageState = "approved" | "review" | "partial" | "running" | "pending" | "inactive" | "failed" | "live";

export interface StageNode {
  id: string;
  type: "prd" | "spec" | "tests" | "collection" | "deploy" | "metrics";
  label: string;
  title: string;
  state: StageState;
  connector: string;
  connectorColor: string;
  detail: string;
  stats?: string;
  actions: string[];
}

export interface Feature {
  id: string;
  name: string;
  team: string;
  stages: StageNode[];
}

export const FEATURES: Feature[] = [
  {
    id: "feat-1",
    name: "Reduce Checkout Friction",
    team: "Payments",
    stages: [
      {
        id: "prd-1", type: "prd", label: "PRD", title: "Reduce Checkout Friction",
        state: "approved", connector: "Linear", connectorColor: "#5e6ad2",
        detail: `**Problem**\nUsers abandon checkout at 40% due to multi-step friction.\n\n**Success Metrics**\n- Abandonment rate < 20%\n- Checkout time < 30s\n- NPS +15 points\n\n**Features**\n- One-click checkout for returning users\n- Remove mandatory 3DS for low-risk < $50\n- Autofill from saved payment methods`,
        actions: ["View in Linear", "Generate Spec"],
      },
      {
        id: "spec-1", type: "spec", label: "Tech Spec", title: "Payment API v2 Refactor",
        state: "review", connector: "Notion", connectorColor: "#ffffff",
        detail: `**Architecture**\nExtend payment-service with quick-checkout flow.\n\n**API Changes**\n\`POST /v2/payments/quick-checkout\`\n\`GET /v2/payments/methods/:userId\`\n\n**Data Models**\n- SavedMethod: { id, last4, brand, expiry }\n- QuickCheckout: { userId, amount, methodId }\n\n**Open Questions**\n- Risk scoring threshold for 3DS bypass\n- Idempotency key strategy`,
        actions: ["View in Notion", "Generate Tests", "Generate Collection"],
      },
      {
        id: "tests-1", type: "tests", label: "Test Cases", title: "5 cases · 3 passing",
        state: "partial", connector: "GitHub CI", connectorColor: "#6e7681",
        stats: "3 / 5",
        detail: `**TC-001** ✅ Happy path quick checkout\n**TC-002** ✅ Invalid card returns 422\n**TC-003** ✅ Idempotent duplicate request\n**TC-004** ❌ High-value 3DS bypass (failing)\n**TC-005** ❌ Expired card handling (failing)\n\n*2 test cases generated by AI, 1 human-written*`,
        actions: ["View in GitHub", "Run All", "Generate More"],
      },
      {
        id: "col-1", type: "collection", label: "API Collection", title: "payments-v2.restol",
        state: "running", connector: "Restol", connectorColor: "#10b981",
        stats: "8 requests",
        detail: `**Collection**: payments-v2\n**Environment**: staging\n**Last run**: 2 min ago · 6/8 passing\n\nPOST /v2/payments/quick-checkout ✅\nGET  /v2/payments/methods/:id ✅\nPOST /v2/payments (legacy) ✅\nDELETE /v2/payments/:id ✅\nPOST /v2/payments/refund ✅\nGET  /v2/payments/status ✅\nPOST /v2/payments/quick-checkout (high-value) ❌\nGET  /v2/payments/methods (empty) ❌`,
        actions: ["Run Collection", "View Results", "Export k6"],
      },
      {
        id: "dep-1", type: "deploy", label: "Deployment", title: "v2.3.0 · staging",
        state: "pending", connector: "ArgoCD", connectorColor: "#f97316",
        detail: `**Version**: payments-service v2.3.0\n**Environment**: staging\n**Status**: Blocked — 2 test cases failing\n**Cluster**: eks-us-east-1\n**Namespace**: payments\n\n*Deploy to prod gated on all tests passing*\n\nRecent deploys:\n- v2.2.9 → prod · 3 days ago ✅\n- v2.2.8 → prod · 8 days ago ✅`,
        actions: ["View in ArgoCD", "View Manifest", "Force Deploy"],
      },
      {
        id: "met-1", type: "metrics", label: "Metrics", title: "Not yet deployed",
        state: "inactive", connector: "Datadog", connectorColor: "#7c3aed",
        detail: `**Dashboard**: payments-v2-prod\n**Status**: Awaiting deployment\n\nWill monitor:\n- Checkout completion rate\n- p99 latency /v2/payments\n- Error rate by endpoint\n- 3DS bypass rate\n\n*Linked to PRD success metrics*`,
        actions: ["Preview Dashboard", "Configure Alerts"],
      },
    ],
  },
  {
    id: "feat-2",
    name: "Payment Method Management",
    team: "Payments",
    stages: [
      {
        id: "prd-2", type: "prd", label: "PRD", title: "Saved Payment Methods UI",
        state: "approved", connector: "Linear", connectorColor: "#5e6ad2",
        detail: "Allow users to manage their saved cards from account settings.",
        actions: ["View in Linear", "Generate Spec"],
      },
      {
        id: "spec-2", type: "spec", label: "Tech Spec", title: "Methods API + UI",
        state: "review", connector: "Notion", connectorColor: "#ffffff",
        detail: "In review with team lead. Covers CRUD endpoints for payment methods.",
        actions: ["View in Notion", "Generate Tests"],
      },
      {
        id: "tests-2", type: "tests", label: "Test Cases", title: "Not generated",
        state: "pending", connector: "—", connectorColor: "#555",
        detail: "Waiting for spec approval before generating test cases.",
        actions: ["Generate Tests"],
      },
      {
        id: "col-2", type: "collection", label: "API Collection", title: "Not created",
        state: "inactive", connector: "—", connectorColor: "#555",
        detail: "Will be auto-generated from spec.",
        actions: ["Generate Collection"],
      },
      {
        id: "dep-2", type: "deploy", label: "Deployment", title: "—",
        state: "inactive", connector: "ArgoCD", connectorColor: "#f97316",
        detail: "No deployment yet.",
        actions: [],
      },
      {
        id: "met-2", type: "metrics", label: "Metrics", title: "—",
        state: "inactive", connector: "Datadog", connectorColor: "#7c3aed",
        detail: "No metrics configured.",
        actions: [],
      },
    ],
  },
];

export interface Connector {
  id: string;
  name: string;
  category: string;
  description: string;
  connected: boolean;
  lastSync?: string;
  color: string;
  icon: string;
  capabilities: string[];
  configFields: { label: string; key: string; type: string }[];
}

export const CONNECTORS: Connector[] = [
  { id: "github", name: "GitHub", category: "Code & CI", description: "Repos, PRs, Actions, Issues", connected: true, lastSync: "2 min ago", color: "#6e7681", icon: "GH", capabilities: ["code", "ci", "issues"], configFields: [{ label: "Personal Access Token", key: "token", type: "password" }, { label: "Organization", key: "org", type: "text" }] },
  { id: "linear", name: "Linear", category: "Issue Tracking", description: "Issues, projects, cycles", connected: true, lastSync: "5 min ago", color: "#5e6ad2", icon: "LN", capabilities: ["issues", "roadmap"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "Team ID", key: "team_id", type: "text" }] },
  { id: "datadog", name: "Datadog", category: "Observability", description: "Metrics, APM, logs, dashboards", connected: true, lastSync: "1 min ago", color: "#7c3aed", icon: "DD", capabilities: ["metrics", "logs", "traces", "alerts"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "App Key", key: "app_key", type: "password" }] },
  { id: "argocd", name: "ArgoCD", category: "Deployment", description: "GitOps deployments, rollbacks", connected: true, lastSync: "3 min ago", color: "#f97316", icon: "AC", capabilities: ["deployments", "rollbacks"], configFields: [{ label: "Server URL", key: "server", type: "text" }, { label: "Auth Token", key: "token", type: "password" }] },
  { id: "coralogix", name: "Coralogix", category: "Logging", description: "Log management and analysis", connected: true, lastSync: "30 sec ago", color: "#06b6d4", icon: "CX", capabilities: ["logs", "alerts"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "Region", key: "region", type: "text" }] },
  { id: "notion", name: "Notion", category: "Docs", description: "Specs, runbooks, wikis", connected: true, lastSync: "15 min ago", color: "#e5e5e5", icon: "NT", capabilities: ["docs"], configFields: [{ label: "Integration Token", key: "token", type: "password" }, { label: "Database ID", key: "database_id", type: "text" }] },
  { id: "eks", name: "Amazon EKS", category: "Kubernetes", description: "Clusters, pods, services, metrics", connected: true, lastSync: "1 min ago", color: "#f59e0b", icon: "EK", capabilities: ["k8s", "infrastructure"], configFields: [{ label: "Cluster Name", key: "cluster", type: "text" }, { label: "Region", key: "region", type: "text" }, { label: "Kubeconfig", key: "kubeconfig", type: "textarea" }] },
  { id: "prometheus", name: "Prometheus", category: "Observability", description: "Self-hosted metrics and alerting", connected: false, color: "#e55b2e", icon: "PR", capabilities: ["metrics", "alerts"], configFields: [{ label: "Endpoint URL", key: "url", type: "text" }, { label: "Basic Auth User", key: "user", type: "text" }, { label: "Basic Auth Password", key: "password", type: "password" }] },
  { id: "newrelic", name: "New Relic", category: "Observability", description: "APM, metrics, browser monitoring", connected: false, color: "#1ce783", icon: "NR", capabilities: ["metrics", "logs", "traces"], configFields: [{ label: "License Key", key: "license_key", type: "password" }, { label: "Account ID", key: "account_id", type: "text" }] },
  { id: "jira", name: "Jira", category: "Issue Tracking", description: "Issues, sprints, epics", connected: false, color: "#0052cc", icon: "JR", capabilities: ["issues", "roadmap"], configFields: [{ label: "Site URL", key: "site", type: "text" }, { label: "API Token", key: "token", type: "password" }, { label: "Email", key: "email", type: "text" }] },
  { id: "loki", name: "Loki", category: "Logging", description: "Log aggregation (Grafana stack)", connected: false, color: "#f9a825", icon: "LK", capabilities: ["logs"], configFields: [{ label: "Endpoint URL", key: "url", type: "text" }, { label: "Org ID", key: "org_id", type: "text" }] },
  { id: "terraform", name: "Terraform Cloud", category: "Infrastructure", description: "IaC runs, state, workspaces", connected: false, color: "#7b42bc", icon: "TF", capabilities: ["infrastructure"], configFields: [{ label: "API Token", key: "token", type: "password" }, { label: "Organization", key: "org", type: "text" }] },
  { id: "pagerduty", name: "PagerDuty", category: "Alerting", description: "Incidents, on-call schedules", connected: false, color: "#06a94d", icon: "PD", capabilities: ["alerts", "incidents"], configFields: [{ label: "API Key", key: "api_key", type: "password" }, { label: "Service ID", key: "service_id", type: "text" }] },
  { id: "gke", name: "Google GKE", category: "Kubernetes", description: "GCP managed Kubernetes", connected: false, color: "#4285f4", icon: "GK", capabilities: ["k8s", "infrastructure"], configFields: [{ label: "Project ID", key: "project_id", type: "text" }, { label: "Cluster Name", key: "cluster", type: "text" }, { label: "Service Account JSON", key: "sa_json", type: "textarea" }] },
];

export const AI_RESPONSES: Record<string, string[]> = {
  "Generate Spec": [
    "Reading PRD: Reduce Checkout Friction...\n",
    "Analyzing success metrics and feature scope...\n",
    "Identifying API surface changes needed...\n\n",
    "**Technical Specification: Payment API v2**\n\n",
    "## Architecture Decision\n",
    "Extend `payment-service` with a dedicated quick-checkout path. Avoids breaking changes to v1 endpoints.\n\n",
    "## New Endpoints\n",
    "```\nPOST /v2/payments/quick-checkout\n  body: { userId, methodId, amount, currency, idempotencyKey }\n  returns: { paymentId, status, requiresAction? }\n```\n\n",
    "## Risk Scoring Integration\n",
    "Call `risk-service` synchronously. If score < 0.3 and amount < $50, skip 3DS. Else fall through to standard flow.\n\n",
    "## Data Model Changes\n",
    "Add `risk_score` and `quick_checkout` flag to `Payment` table. Migration: non-breaking, nullable columns.\n\n",
    "**3 open questions added for team review →**",
  ],
  "Generate Tests": [
    "Reading spec: Payment API v2 Refactor...\n",
    "Extracting API contracts and edge cases...\n\n",
    "**Generating test cases**\n\n",
    "TC-001: Happy path — quick checkout, low-value, no 3DS ✓\n",
    "TC-002: Invalid payment method returns 422 ✓\n",
    "TC-003: Idempotent duplicate request returns same paymentId ✓\n",
    "TC-004: High-value transaction triggers 3DS ✓\n",
    "TC-005: Expired card returns 402 ✓\n",
    "TC-006: Risk score threshold boundary (edge case) ✓\n",
    "TC-007: Concurrent requests with same idempotency key ✓\n\n",
    "**7 test cases created → pushed to GitHub as draft PR**",
  ],
  "Generate Collection": [
    "Reading spec contracts...\n",
    "Parsing endpoint schemas...\n\n",
    "Building collection: payments-v2.restol.yaml\n\n",
    "  POST /v2/payments/quick-checkout — with body + assertions\n",
    "  GET  /v2/payments/methods/:userId — parameterized\n",
    "  POST /v2/payments/quick-checkout (high-value) — edge case\n",
    "  POST /v2/payments/quick-checkout (invalid method) — negative\n",
    "  POST /v2/payments/quick-checkout (duplicate idempotency) — replay\n\n",
    "**Collection saved · 5 requests · ready to run against staging**",
  ],
  "default": [
    "Analyzing context...\n\n",
    "Reading connected sources: Linear, Notion, GitHub CI...\n\n",
    "**Summary**\n\n",
    "Feature is at 60% completion. 2 test cases blocking deployment.\n\n",
    "Recommended next action: fix TC-004 (high-value 3DS) — the spec\nhas a gap in the risk score threshold definition.\n\n",
    "**Ask me**: 'Why is TC-004 failing?' or 'Trace this to the PRD'",
  ],
};
