global:
  scrape_interval: 15s
scrape_configs:
  - job_name: demo-services
    static_configs:
      - targets: ['payments-api:3010','auth-service:3011','checkout-api:3012']
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
rule_files:
  - alerts.yml
